backend:
  name: github
  repo: SofiZapatela/trendmdq
  branch: main
  open_authoring: true

media_folder: "fotos"
public_folder: "/fotos"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Imagen principal", name: "imagen", widget: "image" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["remeras", "pantalones", "abrigos", "tejidos"] }
      - { label: "Stock", name: "stock", widget: "number", value_type: "int" }
