backend:
  name: github
  repo: SofiZapatela/trendmdq
  branch: main
  base_url: https://trendmdq.vercel.app/api
  auth_endpoint: auth
  open_authoring: true
  publish_mode: simple

media_folder: "fotos"
public_folder: "/fotos"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Imagen principal", name: "imagen", widget: "image" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["vestido", "pantalones", "blusa", "campera", "mono", "falda", "conjunto", "chaqueta", "zapatos"] }
      - { label: "Stock", name: "stock", widget: "number", value_type: "int" }